In [1]:
import numpy as np
import matplotlib.pyplot as plt
#from sklearn.preprocessing import normalize
import matplotlib as mpl
import matplotlib.pylab as pl

# Paper font style
rc_fonts = {
    'font.family': 'serif',
    'figure.figsize': (10, 6),
    'text.usetex': True,
    #'text.latex.preview': True,
    'text.latex.preamble': r"\usepackage[cal=euler]{mathalfa} \usepackage{libertine} \usepackage[libertine,smallerops]{newtxmath} \usepackage[T1]{fontenc}"
}

mpl.rcParams.update(rc_fonts)

In [2]:
from sim import sim

In [3]:
d = 100                            # Number of input units 
k = 4                              # Number of teacher hidden units  
p = 8                              # Number of student hidden units 
noise = 1e-3                       # Noise level
t_max = 1e2                        # Maximum t on the respective time scaling
tol = 0                            # Stops if abs(pop_risk_t - pop_risk_{t-1}) <= tol. If zero, stops on alpha_max
save_folder = 'results/run_tests/' # Folder to save
gamma_0 = p                        # Gamma zero

In [4]:
kappa = 0                              # Hidden layer exponent 
delta = 0                              # Learning rate exponent

simul = sim(d,p,k)                      # Initialize the class
Wt = simul.set_teacher(orthWt= True)    # orthWt: whether the teacher is delta_{rs} or not
W0 = simul.set_W0()                     # Gaussian uninformed initialization

t, eg, Wf, _ = simul.fit(alpha_max= t_max, delta=delta, kappa=kappa, eta0= gamma_0, noise= noise, tol= tol, save_folder= save_folder)


'''If necessary to compare with ODEs, save W0 and Wt to construct the respectives Q0, M0 and P'''
#id_ = 'Wt_W0_d%d_p%s_k%s_sit00.npz' % (d,'{:03}'.format(p),'{:03}'.format(k))
#dict_save = {'Wt':Wt, 'W0': W0}
#file_path_id = '/Wt_W0'
#file_path = file_path_id_ + '/' + id_
#np.savez(file_path, **dict_save)

Wt shape=  (100, 4)
      
Wt =  [[-1.37402219e+00 -5.29629125e-01 -1.17147674e+00 -2.36777740e-01]
 [-1.25427768e+00  1.19511491e+00 -2.98415290e-01 -6.99865870e-01]
 [-3.76048809e-01 -1.39737025e+00 -1.39299593e+00 -6.52841417e-02]
 [-1.69392808e+00 -1.62513191e-02 -4.64043087e-01 -3.78788349e-01]
 [-1.20468115e+00  1.27384565e+00  6.62522413e-01  8.81022061e-02]
 [ 1.10312948e+00 -8.97138657e-01  9.95352931e-01 -9.57042935e-01]
 [-9.82013246e-01  1.51725341e+00 -5.79597667e-01  2.97956113e-02]
 [-1.53103471e+00 -5.83253620e-01  2.67957821e-01  8.55895409e-01]
 [ 1.16902725e+00  9.35708079e-01 -1.02887730e+00 -6.91469364e-01]
 [-1.20497532e+00 -1.65395230e-01  7.63590091e-01  1.44925770e+00]
 [ 9.28974145e-01 -5.72157351e-02 -1.74098680e+00  4.89116228e-01]
 [ 9.95622409e-01 -9.12434907e-02 -1.39829683e+00  1.13533690e+00]
 [ 1.60418347e+00 -5.83475154e-01 -5.11001794e-01  3.37630500e-01]
 [ 9.53255826e-01  6.36076365e-01 -1.38910259e+00 -9.47885174e-01]
 [ 3.34033262e-01  2.20180903

'If necessary to compare with ODEs, save W0 and Wt to construct the respectives Q0, M0 and P'

In [9]:
Wt.T @ Wt

array([[ 1.00000000e+02,  3.67227904e-14,  5.92585103e-15,
         1.64721234e-15],
       [ 3.67227904e-14,  1.00000000e+02, -5.59717944e-15,
        -5.29693962e-15],
       [ 5.92585103e-15, -5.59717944e-15,  1.00000000e+02,
         1.04124046e-14],
       [ 1.64721234e-15, -5.29693962e-15,  1.04124046e-14,
         1.00000000e+02]])