In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from rf import rf

In [6]:
d = 100                            # Number of input units 
k = 4                              # Number of teacher hidden units  
p = 200                              # Number of student hidden units 
noise = 0.                       # Noise level
t_max = 1e4                        # Maximum t on the respective time scaling
tol = 0                            # Stops if abs(pop_risk_t - pop_risk_{t-1}) <= tol. If zero, stops on alpha_max
save_folder = 'results/'          # Folder to save
gamma_0 = 1. / np.sqrt(d)

In [7]:
kappa = 0                              # Hidden layer exponent 
delta = 0                              # Learning rate exponent

simul = rf(d,p,k, norm=True)                           # Initialize the class
beta_t  = simul.set_teacher()    # orthWt: whether the teacher is delta_{rs} or not
W0, a0 = simul.set_Theta0()                 # Gaussian uninformed initialization

t, eg, _ , _ = simul.fit(alpha_max= t_max, 
                         delta=delta, 
                         kappa=kappa,
                         lra0= gamma_0,  
                         noise= noise, 
                         tol= tol, 
                         save_folder= save_folder)

- - - RANDOM FEATURES MODEL - - -
Noiseless linear teacher : y_t = Wx/sqrt(d)
Scaling:
BLUE line: kappa + delta = 0
alpha_scale:  d1.0000
d= 100, p= 200, lra= 0.100, noise= 0e+00 -- j= 0, alpha= 0e+00, eg= 0.4894824324, time= 0.00
d = 100, p = 200, lra = 0.100, noise= 0e+00 -- j = 100, alpha = 1e+00, eg = 0.4894175719, time = 3.75
d = 100, p = 200, lra = 0.100, noise= 0e+00 -- j = 200, alpha = 2e+00, eg = 0.4892971745, time = 0.05
d = 100, p = 200, lra = 0.100, noise= 0e+00 -- j = 300, alpha = 3e+00, eg = 0.4891990284, time = 0.05
d = 100, p = 200, lra = 0.100, noise= 0e+00 -- j = 400, alpha = 4e+00, eg = 0.4890969298, time = 0.05
d = 100, p = 200, lra = 0.100, noise= 0e+00 -- j = 500, alpha = 5e+00, eg = 0.4890065272, time = 0.05
d = 100, p = 200, lra = 0.100, noise= 0e+00 -- j = 600, alpha = 6e+00, eg = 0.4889214002, time = 0.06
d = 100, p = 200, lra = 0.100, noise= 0e+00 -- j = 700, alpha = 7e+00, eg = 0.4888139128, time = 0.05
d = 100, p = 200, lra = 0.100, noise= 0e+00 -- j = 800,

In [16]:
a0

array([-2.54935723e-03,  3.77673874e-03,  7.41647717e-04, -5.52794376e-03,
       -4.13974105e-03,  1.80245094e-03,  3.30516382e-03,  8.10091552e-04,
        1.00840351e-02,  8.90563974e-03, -6.70951168e-04, -4.70703712e-03,
       -6.02507761e-03,  6.22922102e-03,  7.87405268e-03, -7.70290064e-04,
        1.29479565e-03, -6.88258351e-04,  1.37152275e-03,  3.31888527e-03,
       -9.59264901e-03, -2.65958712e-03,  1.96894121e-04, -8.82853794e-03,
        3.24555827e-03, -7.59440818e-03, -6.87500312e-03, -4.26775486e-03,
       -4.92510877e-03,  6.09482535e-03, -3.68280239e-03, -1.30594233e-03,
       -5.17713753e-03,  5.38084095e-03,  4.12438238e-03, -6.53847023e-03,
        1.98464452e-03, -7.98919441e-03,  2.19801363e-04, -2.08944949e-03,
        2.66269351e-03, -9.25204514e-03,  2.42042084e-04, -7.14748336e-05,
       -2.51136082e-03,  1.56685180e-03, -8.46179768e-03, -1.74322393e-03,
        6.50964280e-04, -2.80117336e-03,  4.19819651e-03,  6.52137671e-03,
       -6.30752366e-03,  

In [5]:
from sklearn.preprocessing import normalize

In [8]:
Wt =  np.sqrt(d)*normalize(np.random.randn(d, k), axis=1, norm='l2') 

In [7]:
x = np.random.randn(10)

In [10]:
np.linalg.norm(x)

3.400497950401918

In [11]:
np.sqrt(np.sum(x**2))

3.400497950401918

In [19]:
np.sqrt(np.sum(Wt**2, axis=0))

array([10., 10., 10., 10.])

In [20]:
at

NameError: name 'at' is not defined

In [23]:
np.random.randn(d)

array([-0.13855267, -0.6908099 , -1.05336427,  1.06549265, -1.84513417,
        0.99904188,  0.7535509 ,  1.81013023,  0.37599322,  1.79230666,
       -1.32132812,  0.81542589, -0.89501166,  1.41234096, -0.32653368,
        1.05291919, -0.58006631, -0.7240041 , -0.14185634, -0.36210062,
       -0.05232912, -0.42288863,  1.09432221, -1.43435825, -0.9750616 ,
       -1.07207048, -0.67681934, -0.46448065, -0.22178285, -0.62327637,
       -0.51284395,  0.08808244,  0.87260987, -1.66290501,  1.46760691,
        0.15393718, -0.3851833 ,  0.85925704,  0.98295696, -1.17650041,
        0.40629734,  0.98586701, -1.30173241, -0.62043744,  0.29295169,
        0.31361881,  0.04549032, -1.16483391,  0.24182135, -0.73086117,
       -0.9920907 , -0.2743804 , -1.57908144, -0.70381162, -0.90932114,
        0.22821135, -1.22310291, -2.42746239, -0.38128731,  0.18968985,
       -1.1576216 , -1.01403883, -0.08555998, -0.26388534, -0.9045637 ,
        0.46435766, -0.43932823, -0.34561126, -0.28766946,  1.73

In [24]:
X_test = np.random.randn(6, 3)

In [31]:
X_test[:,0]

array([ 0.34084226,  0.41824264, -0.18663397,  0.60695013,  0.03947789,
       -1.16327192])

In [32]:
for j in range(5):
    print(j)

0
1
2
3
4
